name: update-tags

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    name: tag
    runs-on: [ ubuntu-latest ]
    if: ${{ github.event.repository.fork == false }}

    steps:

    - name: Update tags
      uses: actions/github-script@v6
      with:
        script: |
          const version = "${{ github.ref_name }}".split('.')[0];
          let floating = null;
          try {
            floating = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${version}`
            })
          } catch {
          }
          if (floating) {
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${version}`
            })
          }
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${version}`,
            sha: context.sha
          })
